"""Adicionando data de compra em Compras

Revision ID: 0e56c88f19c6
Revises: 7898be66a4aa
Create Date: 2023-10-13 19:41:23.956162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e56c88f19c6'
down_revision = '7898be66a4aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dta_compra', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.drop_column('dta_compra')

    # ### end Alembic commands ###
