"""Trocando lote pra string

Revision ID: 1edf4e004de1
Revises: 984abde7891c
Create Date: 2023-10-11 21:55:51.443194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edf4e004de1'
down_revision = '984abde7891c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.alter_column('lote',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=3),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.alter_column('lote',
               existing_type=sa.String(length=3),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
