"""Ajustes na tabela vendas

Revision ID: 2277dadebbdc
Revises: b3b50f88201c
Create Date: 2023-11-03 16:51:34.346294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2277dadebbdc'
down_revision = 'b3b50f88201c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_cliente', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_vendas_clientes', 'clientes', ['nome_cliente'], ['nome'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('nome_cliente')

    # ### end Alembic commands ###
