"""Adição de coluna 'vendido' no produto

Revision ID: 55e76f869262
Revises: 2277dadebbdc
Create Date: 2023-11-03 20:10:14.537706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55e76f869262'
down_revision = '2277dadebbdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendido', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('vendido')

    # ### end Alembic commands ###
