"""Adicionando tipo de venda

Revision ID: 79890888b2c3
Revises: 0e56c88f19c6
Create Date: 2023-10-18 19:39:34.322118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79890888b2c3'
down_revision = '0e56c88f19c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_venda', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_column('tipo_venda')

    # ### end Alembic commands ###
