"""Trocando val_total_pg  pra float

Revision ID: 8e1144927a96
Revises: 1edf4e004de1
Create Date: 2023-10-11 22:15:38.651742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1144927a96'
down_revision = '1edf4e004de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.alter_column('val_total_pg',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compras', schema=None) as batch_op:
        batch_op.alter_column('val_total_pg',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
