"""Ajuste tabela produto_vendas

Revision ID: dfe23d221219
Revises: 415e4bad0ff0
Create Date: 2023-11-20 22:01:54.273662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfe23d221219'
down_revision = '415e4bad0ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos_vendas',
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.Column('id_venda', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['id_venda'], ['vendas.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos_vendas')
    # ### end Alembic commands ###
