"""Adição do tipo_desconto na venda

Revision ID: f58c5764625b
Revises: 6897a5b4f967
Create Date: 2024-01-12 21:01:08.026137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f58c5764625b'
down_revision = '6897a5b4f967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_desconto', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_column('tipo_desconto')

    # ### end Alembic commands ###
